### ISSUE TITLE
Work wont work.

### ISSUE THREAD

**Issue by ghgiStudios** [KozmikNano/KozmikServices#1]
When importing the ONC file the password and PSK is not saved and when adding manually it says "error configuring network", what could this mean?

**Comment by KozmikNano** [comment]
This may mean that your admin has blocked VPN configurations via policies. What version of chrome are you using?

**Comment by NideZ60** [comment]
> When importing the ONC file the password and PSK is not saved and when adding manually it says "error configuring network", what could this mean?

Ive also had the same problem, i think its due to the admin policy on the Chromebooks, if you aren't able to edit VPN settings you wont be able to connect to one.

**Comment by KozmikNano** [comment]
I have talked to some others with this issue and that is correct!
