### ISSUE TITLE
Won't Connect

### ISSUE THREAD

**Issue by thedudemeister08** [KozmikNano/KozmikServices#3]
Can you please fix this because none of the releases are connecting they just say connecting but then they fail. 
![Screenshot 2022-09-30 12 34 16 PM](https://user-images.githubusercontent.com/95984178/193325554-21177273-a7ae-4790-90ca-d684140325cf.png)
![Screenshot 2022-09-30 12 33 38 PM](https://user-images.githubusercontent.com/95984178/193325559-52c8ffb4-a7d4-4ee6-b3d2-a16b69d0d42b.png)

**Comment by KozmikNano** [comment]
Fixed, please check the releases tab
